### ISSUE TITLE
[CY-4150] Java jar test error

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [codacy/codacy-analysis-cli#365]
Hello, I tried to run this on the [latest jar release](https://github.com/codacy/codacy-analysis-cli/releases/tag/6.1.0) : 

```shell_session
 $ java -jar codacy-analysis-cli-assembly-6.1.0.jar analyze \
        --tool brakeman \
        --directory ~/GIT/tabbed
```
And I got this error : `java.lang.NoClassDefFoundError: org/xml/sax/InputSource`

<details>

```
Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: org/xml/sax/InputSource
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:108)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at com.codacy.analysis.cli.formatter.Formatter$.<init>(Formatter.scala:33)
	at com.codacy.analysis.cli.formatter.Formatter$.<clinit>(Formatter.scala)
	at com.codacy.analysis.cli.command.Analyze$.apply$default$5(CLIApp.scala:132)
	at com.codacy.analysis.cli.command.CLIApp$anon$generic$macro$309$1.inst$macro$32$lzycompute(CLIApp.scala:17)
	at com.codacy.analysis.cli.command.CLIApp$anon$generic$macro$309$1.inst$macro$32(CLIApp.scala:17)
	at com.codacy.analysis.cli.command.CLIApp$anon$generic$macro$309$1.inst$macro$31$lzycompute(CLIApp.scala:17)
	at com.codacy.analysis.cli.command.CLIApp$anon$generic$macro$309$1.inst$macro$31(CLIApp.scala:17)
	at com.codacy.analysis.cli.command.CLIApp.<init>(CLIApp.scala:17)
	at com.codacy.analysis.cli.MainImpl.<init>(Main.scala:11)
	at com.codacy.analysis.cli.Main$.<init>(Main.scala:6)
	at com.codacy.analysis.cli.Main$.<clinit>(Main.scala)
	at com.codacy.analysis.cli.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: org.xml.sax.InputSource
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 22 more
Exception in thread "main" java.lang.NoClassDefFoundError: org/xml/sax/InputSource
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:108)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at com.codacy.analysis.cli.formatter.Formatter$.<init>(Formatter.scala:33)
	at com.codacy.analysis.cli.formatter.Formatter$.<clinit>(Formatter.scala)
	at com.codacy.analysis.cli.command.Analyze$.apply$default$5(CLIApp.scala:132)
	at com.codacy.analysis.cli.command.CLIApp$anon$generic$macro$309$1.inst$macro$32$lzycompute(CLIApp.scala:17)
	at com.codacy.analysis.cli.command.CLIApp$anon$generic$macro$309$1.inst$macro$32(CLIApp.scala:17)
	at com.codacy.analysis.cli.command.CLIApp$anon$generic$macro$309$1.inst$macro$31$lzycompute(CLIApp.scala:17)
	at com.codacy.analysis.cli.command.CLIApp$anon$generic$macro$309$1.inst$macro$31(CLIApp.scala:17)
	at com.codacy.analysis.cli.command.CLIApp.<init>(CLIApp.scala:17)
	at com.codacy.analysis.cli.MainImpl.<init>(Main.scala:11)
	at com.codacy.analysis.cli.Main$.<init>(Main.scala:6)
	at com.codacy.analysis.cli.Main$.<clinit>(Main.scala)
	at com.codacy.analysis.cli.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: org.xml.sax.InputSource
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 22 more
```
</details>

________

| System       | Linux          |
|--------------|----------------|
| Distribution | NixOS          |
| Architecture | x86_64         |
| java version | openjdk 15.0.1 |

**Comment by josemiguelmelo** [comment]
Hi @SCOTT-HAMILTON ,

We tried to reproduce the error without success.

To try to reproduce, we installed NixOS inside a docker container (used this [docker image](https://hub.docker.com/r/nixos/nix)) and we tried to run the Codacy Analysis CLI on nix-shell (to start the shell, we used `nix-shell -p openjdk`).

Can you give us some steps to be able to reproduce the error?

Thank you,

**Comment by SCOTT-HAMILTON** [comment]
Hello, thanks for the callback. I've tried to make a reproducible nix-shell but it didn't work.
After some more investigations, I came to the conclusion that I was using an old openjdk java.

The version that was an OpenJDK General Application version 15.0.1.

Reinstalling openjdk fixed my issue.

Thanks for helping !
